config/routes.rb
#   new_admin_section_class_student_class GET    /admin/section_classes/:section_class_id/student_class/new(.:format)                     admin/student_class#new
#  edit_admin_section_class_student_class GET    /admin/section_classes/:section_class_id/student_class/:id/edit(.:format)                admin/student_class#edit
#       admin_section_class_student_class GET    /admin/section_classes/:section_class_id/student_class/:id(.:format)                     admin/student_class#show
#                                         PATCH  /admin/section_classes/:section_class_id/student_class/:id(.:format)                     admin/student_class#update
#                                         PUT    /admin/section_classes/:section_class_id/student_class/:id(.:format)                     admin/student_class#update
#                                         DELETE /admin/section_classes/:section_class_id/student_class/:id(.:format)                     admin/student_class#destroy
#                   admin_section_classes GET    /admin/section_classes(.:format)                                                         admin/section_classes#index
#                                         POST   /admin/section_classes(.:format)                                                         admin/section_classes#create
#                 new_admin_section_class GET    /admin/section_classes/new(.:format)                                                     admin/section_classes#new
#                edit_admin_section_class GET    /admin/section_classes/:id/edit(.:format)                                                admin/section_classes#edit
#                     admin_section_class GET    /admin/section_classes/:id(.:format)                                                     admin/section_classes#show
#                                         PATCH  /admin/section_classes/:id(.:format)                                                     admin/section_classes#update
#                                         PUT    /admin/section_classes/:id(.:format)                                                     admin/section_classes#update
#                                         DELETE /admin/section_classes/:id(.:format)                                                     admin/section_classes#destroy
#                           lecturer_root GET    /lecturer(.:format)                                                                      lecturer/home#index
#                       lecturer_students GET    /lecturer/students(.:format)                                                             lecturer/students#index
#                                         POST   /lecturer/students(.:format)                                                             lecturer/students#create
#                    new_lecturer_student GET    /lecturer/students/new(.:format)                                                         lecturer/students#new
#                   edit_lecturer_student GET    /lecturer/students/:id/edit(.:format)                                                    lecturer/students#edit
#                        lecturer_student GET    /lecturer/students/:id(.:format)                                                         lecturer/students#show
#                                         PATCH  /lecturer/students/:id(.:format)                                                         lecturer/students#update
#                                         PUT    /lecturer/students/:id(.:format)                                                         lecturer/students#update
#                                         DELETE /lecturer/students/:id(.:format)                                                         lecturer/students#destroy
#                       lecturer_subjects GET    /lecturer/subjects(.:format)                                                             lecturer/subjects#index
#                                         POST   /lecturer/subjects(.:format)                                                             lecturer/subjects#create
#                    new_lecturer_subject GET    /lecturer/subjects/new(.:format)                                                         lecturer/subjects#new
#                   edit_lecturer_subject GET    /lecturer/subjects/:id/edit(.:format)                                                    lecturer/subjects#edit
#                        lecturer_subject GET    /lecturer/subjects/:id(.:format)                                                         lecturer/subjects#show
#                                         PATCH  /lecturer/subjects/:id(.:format)                                                         lecturer/subjects#update
#                                         PUT    /lecturer/subjects/:id(.:format)                                                         lecturer/subjects#update
#                                         DELETE /lecturer/subjects/:id(.:format)                                                         lecturer/subjects#destroy
#                   lecturer_score_boards GET    /lecturer/score_boards(.:format)                                                         lecturer/score_boards#index
#                                         POST   /lecturer/score_boards(.:format)                                                         lecturer/score_boards#create
#                new_lecturer_score_board GET    /lecturer/score_boards/new(.:format)                                                     lecturer/score_boards#new
#               edit_lecturer_score_board GET    /lecturer/score_boards/:id/edit(.:format)                                                lecturer/score_boards#edit
#                    lecturer_score_board GET    /lecturer/score_boards/:id(.:format)                                                     lecturer/score_boards#show
#                                         PATCH  /lecturer/score_boards/:id(.:format)                                                     lecturer/score_boards#update
#                                         PUT    /lecturer/score_boards/:id(.:format)                                                     lecturer/score_boards#update
#                                         DELETE /lecturer/score_boards/:id(.:format)                                                     lecturer/score_boards#destroy
#                lecturer_section_classes GET    /lecturer/section_classes(.:format)                                                      lecturer/section_classes#index
#                                         POST   /lecturer/section_classes(.:format)                                                      lecturer/section_classes#create
#              new_lecturer_section_class GET    /lecturer/section_classes/new(.:format)                                                  lecturer/section_classes#new
#             edit_lecturer_section_class GET    /lecturer/section_classes/:id/edit(.:format)                                             lecturer/section_classes#edit
#                  lecturer_section_class GET    /lecturer/section_classes/:id(.:format)                                                  lecturer/section_classes#show
#                                         PATCH  /lecturer/section_classes/:id(.:format)                                                  lecturer/section_classes#update
#                                         PUT    /lecturer/section_classes/:id(.:format)                                                  lecturer/section_classes#update
#                                         DELETE /lecturer/section_classes/:id(.:format)                                                  lecturer/section_classes#destroy
#                      rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#               rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                      rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#               update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                    rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get '/test', to: 'homes#test'
  get '/rake', to: 'homes#rake'
  get '/new_password', to: 'homes#new_pass'
  post '/new_password', to: 'homes#change_pass'
  get '/measurement_plan', to: 'homes#measurement_plan'
  get '/documents/approve/:id', to: 'documents#approve'
  get '/documents/view/:id', to: 'documents#view'
  resources :messages
  resources :documents
  resources :rooms
  resources :members
  namespace :admin do
    root 'home#index'
    resources :users
    get '/user/import', to: 'users#import'
    post '/user/import', to: 'users#import_data'
    resources :subjects do
      resources :score_types
      resources :abet_levels
      resources :learning_outcomes do
        resources :lo_types
      end
    end
    resources :original_classes
    resources :students
    resources :section_classes do
      resources :permissions
      resources :student_class
    end
    resources :so do
      resources :pi do
        resources :pi_lo do
        end
      end
    end
  end
  namespace 'lecturer' do
    root 'home#index'
    resources :students
    resources :subjects
    resources :score_boards
    resources :section_classes do
      post :export
      resources :score_boards do
      end
    end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_rooms_on_user_id  (user_id)
#
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :delete_all
  has_many :members, dependent: :delete_all
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :init
  def index
  end

  def new
  end

  def init
    mem = Member.where(user_id: current_user.id)
    @rooms = Room.where(id: mem.pluck(:room_id))
    @room = params[:id].present? ? Room.find(params[:id]) : Room.new
    @rooms = Room.all if current_user.admin?
  end

  def create
    room = Room.create(
      name: params['room']['name'],
      user_id: current_user.id
    )
    Member.create(room_id: room.id, user_id: current_user.id, owner: true)
    mem = Member.where(user_id: current_user.id)
    @rooms = Room.where(id: mem.pluck(:room_id))
    render :index
  end

  def show
    @mes = Message.where(room_id: params[:id])
    @members = Member.where(room_id: params[:id])
    @owner = @members.find_by(user_id: current_user.id).owner
  end

  def destroy
    @room.destroy
    redirect_to rooms_url
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_message.html.erb
<%
  is_me = is_me || false
%>
<div class='row'>
  <div class='col-9 p-0 <%= 'text-end' if is_me%>'>
    <h5><%= name if !is_me %></h5>
    <div class = 'p-3 border border-rounded border-primary mess-box'>
      <%= content %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='p-5'>
  <h3><%= I18n.t('rooms') %> > <%= I18n.t('list') %></h3>
  <hr/>
  <a href='/rooms/new'><button class='btn btn-outline-success'>+</button></a>
  <%# <%= render 'layouts/input/search' %>
  <table class="table caption-top">
    <thead>
      <tr>
        <th scope="col"><%= I18n.t("name") %></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.name %></td>
          <td class="d-flex justify-content-end">
            <%unless current_user.admin?%>
              <a href='<%= room_path(room.id)%>'><i class="fas fa-angle-double-right"></i></a>
            <%end%>
            <% if current_user.admin? %>
              <a href='/rooms/<%=room.id%>' data-method="DELETE" onclick="if (confirm('Delete selected item?')){return true;}else{event.stopPropagation(); event.preventDefault();};"><i class="mx-1 fas fa-trash-alt"></i></a>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="pagination d-flex justify-content-center">
    <%# <%= will_paginate @docs, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='p-5'>
  <h3><%= I18n.t('rooms') %> > <%= I18n.t('new') %></h3>
  <%= form_for @room, :html => {:multipart => true} do |form| %>
    <div class="field form-group mt-2">
      <label><%=I18n.t('name')%><span class="text-danger">*</span></label>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <%= render 'layouts/input/action' %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class='py-3 px-5 row'>
  <h3><b><%= @room.name %></b></h3>
  <div class='chat-box p-2 border border-primary col-9'>
    <div class='chat-frame', id='chat-frame'>
      <div id='chat-box'>
      
      </div>
      <div id='bottom-chat'></div>
    </div>
    <hr/>
    <div class=row>
      <div class='col-10'>
        <input type='text' class='form-control' id='current-text' name='search' >
      </div>
      <div class='col-2'>
        <button id='send_button' class='btn btn-success' onclick='send_mess()'><%=I18n.t('send')%></button>
      </div>
    </div>
  </div>

  <div class='col-3 border border-primary py-4'>
    <div class='text-center'><h3><%= I18n.t('members') %></h3></div>
    <% @members.each do |mem| %>
      <div><%= mem.user.full_name %></div>
    <% end %>
    <!-- Button trigger modal -->
    <%if @owner %>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <%= I18n.t('member.add') %>
      </button>
    <% end %>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><%= I18n.t('member.add')%></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method='post' class='m-4' action='/members'>
            <input name='room_id' type='hidden' value='<%=@room.id%>'>
            <%=
              @members = Member.where(room_id: params[:id])
              render 'layouts/input/select',
              list: User.where(role: ['lecturer', 'manage']).where.not(id: @members.pluck(:id)),
              name: 'user_id',
              label: 'members'
            %>
            <button type="submit" class="btn btn-primary">Add</button>
          </form>
        </div>
      </div>
    </div>


  </div>
</div>
<script>
  var mess_id = 0;

  // var myModal = document.getElementById('myModal')
  // var myInput = document.getElementById('myInput')

  // myModal.addEventListener('shown.bs.modal', function () {
  //   myInput.focus()
  // })
  
  load();

  document.addEventListener("keypress", function(event) {
    if (event.keyCode == 13) {
      send_mess();
    }
  });

  function send_mess(){
    text = document.getElementById('current-text').value
    chat_box = document.getElementById('chat-box')
    if (text == ''){
      return;
    }else{
      axios.post('/messages', {
      room_id: '<%= @room.id %>',
      content: text
      });
    }
    document.getElementById('current-text').value = '';
  }
  function load_new_mess(content, name, time, is_me){
    text_end = is_me ? 'text-end' : '';
    name = is_me ?  '' : `<div style='padding-top: 1rem'>${name}</div>`;
    html = 
    `
    <div>
      <div class='px-4 ${text_end}'>
      ${name}
      <div class='time'>${time}</div>
      <div class = 'p-3 border border-rounded border-primary mess-box'>
          ${content}
        </div>
      <div>
    </div>
    `;
    chat_box = document.getElementById('chat-box');
    chat_box.insertAdjacentHTML('beforeend', html);
    
    return html;
  }
  
  async function load(){
    var myDiv = document.getElementById("chat-frame");
    scroll = true;
    while(true){
      await axios.get(`/messages?room_id=<%=@room.id%>&mess_id=${mess_id}`).then(function(response){
        response.data.forEach(parse_data);
        
      });
      if (scroll) {
        myDiv.scrollTop = myDiv.scrollHeight;
        scroll = false;
      }
      await stop(2000);
    }
  }

  function parse_data(value, index, array) {
    mess_id = value.id;
    current_user_id = '<%= current_user.id %>';
    content = value.content;
    user_id = value.user_id;
    name = value.full_name;
    time = value.time
    load_new_mess(content, name, time, current_user_id == user_id);
  }

  
</script>